import React from 'react';
import '../styles/PrivacyPolicy.css';

const PrivacyPolicy = () => {
  return (
    <div className="privacy-page">
      <div className="privacy-container">
        <div className="privacy-header">
          <h1 className="privacy-title">Privacy Policy</h1>
          <p className="privacy-subtitle">We value your privacy and are committed to protecting your personal data.</p>
          <div className="privacy-divider"></div>
        </div>

        <div className="privacy-content">
          {/* Introduction */}
          <section className="privacy-section">
            <h2 className="section-title">Introduction</h2>
            <p className="section-text">
              Welcome to Inzavy. Our Privacy Policy governs your visit to inzavy.com and explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy.
            </p>
          </section>

          {/* Definitions */}
          <section className="privacy-section">
            <h2 className="section-title">Definitions</h2>
            <div className="definition-list">
              <div className="definition-item">
                <strong>SERVICE</strong> means the Inzavy.com website operated by Inzavy.
              </div>
              <div className="definition-item">
                <strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data.
              </div>
              <div className="definition-item">
                <strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself.
              </div>
              <div className="definition-item">
                <strong>COOKIES</strong> are small files stored on your device (computer or mobile device).
              </div>
              <div className="definition-item">
                <strong>DATA CONTROLLER</strong> means a natural or legal person who determines the purposes for which and the manner in which any personal data are processed.
              </div>
              <div className="definition-item">
                <strong>DATA PROCESSORS</strong> means any natural or legal person who processes the data on behalf of the Data Controller.
              </div>
              <div className="definition-item">
                <strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.
              </div>
              <div className="definition-item">
                <strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject.
              </div>
            </div>
          </section>

          {/* Information Collection */}
          <section className="privacy-section">
            <h2 className="section-title">Information Collection and Use</h2>
            <p className="section-text">
              We collect several different types of information for various purposes to provide and improve our Service to you.
            </p>

            <h3 className="subsection-title">Types of Data Collected</h3>
            
            <h4 className="subheading">Personal Data</h4>
            <p className="section-text">
              While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include:
            </p>
            <ul className="info-list">
              <li>Email address</li>
              <li>Full Name</li>
              <li>Phone number</li>
              <li>Address, Country, State, Province, ZIP/Postal code, City</li>
              <li>Cookies and Usage Data</li>
            </ul>

            <h4 className="subheading">Usage Data</h4>
            <p className="section-text">
              We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device. This Usage Data may include information such as your computer's Internet Protocol address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>

            <h4 className="subheading">Location Data</h4>
            <p className="section-text">
              We may use and store information about your location if you give us permission to do so. We use this data to provide features of our Service, to improve and customize our Service. You can enable or disable location services when you use our Service at any time by way of your device settings.
            </p>

            <h4 className="subheading">Tracking Cookies Data</h4>
            <p className="section-text">
              We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
            </p>
            <ul className="info-list">
              <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
              <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
              <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
              <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
            </ul>
          </section>

          {/* Use of Data */}
          <section className="privacy-section">
            <h2 className="section-title">Use of Data</h2>
            <p className="section-text">Inzavy uses the collected data for various purposes:</p>
            <ul className="info-list">
              <li>to provide and maintain our Service</li>
              <li>to notify you about changes to our Service</li>
              <li>to allow you to participate in interactive features of our Service when you choose to do so</li>
              <li>to provide customer support</li>
              <li>to gather analysis or valuable information so that we can improve our Service</li>
              <li>to monitor the usage of our Service</li>
              <li>to detect, prevent and address technical issues</li>
              <li>to fulfill any other purpose for which you provide it</li>
              <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us</li>
              <li>to provide you with notices about your account and/or subscription</li>
              <li>to provide you with news, special offers and general information about other goods, services and events</li>
            </ul>
          </section>

          {/* Data Protection Rights */}
          <section className="privacy-section">
            <h2 className="section-title">Your Data Protection Rights Under GDPR</h2>
            <p className="section-text">
              If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <a href="mailto:contact@inzavy.com" className="email-link">contact@inzavy.com</a>.
            </p>
            <p className="section-text">In certain circumstances, you have the following data protection rights:</p>
            <ul className="info-list">
              <li>the right to access, update or to delete the information we have on you</li>
              <li>the right of rectification</li>
              <li>the right to object</li>
              <li>the right of restriction</li>
              <li>the right to data portability</li>
              <li>the right to withdraw consent</li>
            </ul>
          </section>

          {/* CCPA Rights */}
          <section className="privacy-section">
            <h2 className="section-title">Your Data Protection Rights under CCPA</h2>
            <p className="section-text">
              If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
            </p>
            <ul className="info-list">
              <li>What personal information we have about you</li>
              <li>To delete your personal information</li>
              <li>To stop selling your personal information</li>
            </ul>
            <p className="section-text">
              To exercise your California data protection rights described above, please send your request(s) by email: <a href="mailto:contact@inzavy.com" className="email-link">contact@inzavy.com</a>
            </p>
          </section>

          {/* Security */}
          <section className="privacy-section">
            <h2 className="section-title">Security of Data</h2>
            <p className="section-text">
              The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
            </p>
          </section>

          {/* Children's Privacy */}
          <section className="privacy-section">
            <h2 className="section-title">Children's Privacy</h2>
            <p className="section-text">
              Our Services are not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
            </p>
          </section>

          {/* Changes to Policy */}
          <section className="privacy-section">
            <h2 className="section-title">Changes to This Privacy Policy</h2>
            <p className="section-text">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          {/* Contact Us */}
          <section className="privacy-section contact-section">
            <h2 className="section-title">Contact Us</h2>
            
            <div className="contact-grid">
              <div className="contact-card">
                <div className="contact-icon">📍</div>
                <h3 className="contact-card-title">Head Office Address</h3>
                <p className="contact-detail">Office Number 13, G7 Mall, Seven Bunglow, Versova, Andheri West, Mumbai 400061</p>
              </div>

              <div className="contact-card">
                <div className="contact-icon">📱</div>
                <h3 className="contact-card-title">WhatsApp Assistance</h3>
                <p className="contact-detail">Quick Resolutions</p>
                <a href="https://wa.me/919000206900" className="contact-link" target="_blank" rel="noopener noreferrer">Ask on WhatsApp</a>
              </div>

              <div className="contact-card">
                <div className="contact-icon">📞</div>
                <h3 className="contact-card-title">Calling No. (11AM - 8PM)</h3>
                <p className="contact-detail">Leave us a miss call we will get back to you soon</p>
                <a href="tel:+919000206900" className="contact-link">+91 9000206900</a>
              </div>

              <div className="contact-card">
                <div className="contact-icon">🕒</div>
                <h3 className="contact-card-title">Working Hours</h3>
                <p className="contact-detail">Mon-Sat (11 AM to 8 PM)</p>
              </div>

              <div className="contact-card">
                <div className="contact-icon">✉️</div>
                <h3 className="contact-card-title">Email</h3>
                <a href="mailto:contact@inzavy.com" className="contact-link">contact@inzavy.com</a>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
